[SERVICE]
    Flush        5
    Log_Level    info
    Daemon       off

[INPUT]
    Name              tail
    Path              /logs/springboot.log
    Tag               springboot.logs
    Read_from_Head    true

[OUTPUT]
    Name              azure
    Match             *
    Customer_ID       eb0b09b0-78e0-4862-8450-e05561a9dba7
    Shared_Key        3qNxWT9U696neO78EmnauFCfwQ1XIuslDTVwaVuLMUHNXbdH9Ieg8HsJcICebIhnW47Cpq0TJB61eFTAMfsuTA==
    Log_Type          SpringBoot
