apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: rahul-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: springboot-app

  template:
    metadata:
      labels:
        app: springboot-app

    spec:

      volumes:
      - name: logs-volume
        persistentVolumeClaim:
          claimName: logs-pvc

      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config


      containers:

      # Main application container
      - name: springboot-app
        image: runity77/sidecar:v1

        ports:
        - containerPort: 8081

        volumeMounts:
        - name: logs-volume
          mountPath: /logs


      # Fluent Bit sidecar
      - name: fluent-bit
        image: fluent/fluent-bit:latest

        volumeMounts:
        - name: logs-volume
          mountPath: /logs

        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
